### ISSUE TITLE
Ability to align graphs to first reported case(s)

### ISSUE THREAD

**Issue by dstudzinski** [kwasniew/covid.reports#1]
Hi,

Thank you for your page. It's really helpful. One feature that I'm missing is the ability to start all graphs from first reported case(s). It helps to compare how the virus spreads in different countries.

I created PR with change (it's quick & dirty, I have problems with css locally so I can't align label, I will try to fix it if you are interested in this change).

**Comment by kwasniew** [comment]
I will check your PR soon

**Comment by kwasniew** [comment]
I really like the capability to compare from day zero and want to include it in the app. I will start doing code review in a second.

**Comment by kwasniew** [comment]
Done in commit https://github.com/kwasniew/covid.reports/commit/4a5427e51141a48421bbde15c2fb6553e6aefac0
